services:
  - type: web
    name: foodmood
    env: python
    plan: free
    buildCommand: pip install -r sentiment_app/requirements.txt
    startCommand: gunicorn --chdir sentiment_app app:app
    autoDeploy: true
